# For additional unix tools in a small image use one of these:
# FROM busybox
# FROM phusion/baseimage
FROM scratch
MAINTAINER Bryan-Kirk Reinhardt

ADD ringoexp /ringoexp

CMD []

ENTRYPOINT ["/ringoexp", "-N", "Demo", "-H", "0.0.0.0", "-T", "6661"]

# 6660 is used for inbound connections
# 6061 is used for outbound consumer connections.
# 6060 is exposed as a profiler port if you ever need it.
EXPOSE 6660 6661 6060
